name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(grep '"version"' package.json | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.b.picoquant.com
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            git.b.picoquant.com/ruettinger/support-planner:${{ steps.version.outputs.version }}
            git.b.picoquant.com/ruettinger/support-planner:latest
